### ISSUE TITLE
Document in the `loaderFactory` in the docs

### ISSUE THREAD

**Issue by Straightline** [feathers-plus/batch-loader#9]
While perusing the docs, I noticed that the `loaderFactory` static method is not documented in the batchLoader docs. But, it is mentioned in the `fastJoin` docs here: https://feathers-plus.github.io/v1/feathers-hooks-common/#fastjoin 

I know this method exists and works well and would be happy to open a PR when I get a chance.

**Comment by matiaslopezd** [comment]
+1 please! :pray:

**Comment by DaddyWarbucks** [comment]
This has now been documented in the README. I am currently working on adding this to the docs site as well.
